export enum TypeActivityRecord {
    HEAVY = 'HEAVY',
    MEDIUM = 'MEDIUM',
    LIGHT = 'LIGHT',
}
export enum TypeDate {
    MONDAY = 'MONDAY',
    TUESDAY = 'TUESDAY',
    WEDNESDAY = 'WEDNESDAY',
    THURSDAY = 'THURSDAY',
    FRIDAY = 'FRIDAY',
    SATURDAY = 'SATURDAY',
    SUNDAY = 'SUNDAY'
}
export enum Notification {
    DAILY_NOTIFICATION = "DAILY_NOTIFICATION",
    PLAN_NOTIFICATION = "PLAN_NOTIFICATION",
    WEEKLY_REPORT_NOTIFICATION = "WEEKLY_REPORT_NOTIFICATION",
    MONTHLY_REPORT_NOTIFICATION = "MONTHLY_REPORT_NOTIFICATION",
    QUESTION_NOTIFICATION = "QUESTION_NOTIFICATION",
    MEDICAL_APPOINTMENT_NOTIFICATION = "MEDICAL_APPOINTMENT_NOTIFICATION",
}