export const IMAGE = {
    HOME: {
        CATEGORY: require('assets/image/home/category.png'),
        CATEGORY1: require('assets/image/home/category/category1.png'),
        CATEGORY2: require('assets/image/home/category/category2.png'),
        CATEGORY3: require('assets/image/home/category/category3.png'),
        CATEGORY4: require('assets/image/home/category/category4.png'),
        CATEGORY5: require('assets/image/home/category/category5.png'),
        CATEGORY6: require('assets/image/home/category/category6.png'),
        SHOE: require('assets/image/home/shoe.png'),
        CLOCK: require('assets/image/home/clock.png'),
        WARNING_ORANGE: require('assets/image/planmanagement/warning-orange.png'),
        WARNING: require('assets/image/planmanagement/warning.png'),
    },
    REGISTER: {
        BRAIN: require('assets/image/register/brain.png'),
        HEART: require('assets/image/register/heart.png'),
        LUNGS: require('assets/image/register/lungs.png'),
        STETHOSCOPE: require('assets/image/register/stethoscope.png'),
        EMAIL_POLYGON: require('assets/image/register/Polygon.png'),
        EMAIL_RECTANGLE: require('assets/image/register/Rectangle.png'),
        EMAIL_UNION: require('assets/image/register/Union.png'),
    },
    ICON_CHECK: require('assets/icon/icon-check.png'),
    ICON_CHECK_COLOR: require('assets/icon/icon_check-color.png'),
    ICON_SIDEBAR: require('assets/icon/icon-sidebar.png'),
    ICON_INFOR: require('assets/icon/icon-infor.png'),
    ICON_SETTING: require('assets/icon/icon-setting.png'),
    ICON_X: require('assets/icon/icon-X.png'),
    ICON_X_BG_GRAY: require('assets/icon/icon_X_bgGray.png'),
    ICON_ARROW_LEFT: require('assets/icon/icon-arrow_left.png'),
    ICON_ARROW_LEFT_BLACK: require('assets/icon/icon-arrow_left-black.png'),
    ICON_ARROW_RIGHT: require('assets/icon/icon-arrow_right.png'),
    ICON_ARROW_RIGHT_GRAY: require('assets/icon/icon-arrow_right_gray.png'),

};
