export const IMAGE = {
  HOME: {
    CATEGORY: require('assets/image/home/category.png'),
    CATEGORY1: require('assets/image/home/category/category1.png'),
    CATEGORY2: require('assets/image/home/category/category2.png'),
    CATEGORY3: require('assets/image/home/category/category3.png'),
    CATEGORY4: require('assets/image/home/category/category4.png'),
    CATEGORY5: require('assets/image/home/category/category5.png'),
    CATEGORY6: require('assets/image/home/category/category6.png'),
    SHOE: require('assets/image/home/shoe.png'),
    CLOCK: require('assets/image/home/clock.png'),
    WARNING_ORANGE: require('assets/image/planmanagement/warning-orange.png'),
    WARNING: require('assets/image/planmanagement/warning.png'),
    SIDEBAR: {
      프로필이미지: require('assets/image/home/sidebar/프로필이미지.png'),
      ICON_PLAN: require('assets/icon/home/icon-plan.png'),
      ICON_RECORD: require('assets/icon/home/icon-record.png'),
      ICON_REPORT: require('assets/icon/home/icon-report.png'),
      ICON_STUDY: require('assets/icon/home/icon-study.png'),
      ICON_MESSAGE: require('assets/icon/home/icon-message.png'),
      ICON_SETTING: require('assets/icon/home/icon-setting.png'),
    },
    GUIDE: {
      GUIDE1: require('assets/image/home/guide/guide1.png'),
      POLYGON3: require('assets/image/home/guide/polygon-3.png'),
      ICON_DOCTOR: require('assets/image/home/guide/icon-doctor.png'),
    },
  },
  REGISTER: {
    BRAIN: require('assets/image/register/brain.png'),
    HEART: require('assets/image/register/heart.png'),
    LUNGS: require('assets/image/register/lungs.png'),
    STETHOSCOPE: require('assets/image/register/stethoscope.png'),
    EMAIL_POLYGON: require('assets/image/register/Polygon.png'),
    EMAIL_RECTANGLE: require('assets/image/register/Rectangle.png'),
    EMAIL_UNION: require('assets/image/register/Union.png'),
  },
  ICON_CHECK: require('assets/icon/icon-check.png'),
  ICON_CHECK_COLOR: require('assets/icon/icon_check-color.png'),
  ICON_SIDEBAR: require('assets/icon/icon-sidebar.png'),
  ICON_INFOR: require('assets/icon/icon-infor.png'),
  ICON_SETTING: require('assets/icon/icon-setting.png'),
  ICON_X: require('assets/icon/icon-X.png'),
  ICON_X_BG_GRAY: require('assets/icon/icon_X_bgGray.png'),
  ICON_ARROW_LEFT: require('assets/icon/icon-arrow_left.png'),
  ICON_ARROW_LEFT_BLACK: require('assets/icon/icon-arrow_left-black.png'),
  ICON_ARROW_RIGHT: require('assets/icon/icon-arrow_right.png'),
  ICON_ARROW_RIGHT_GRAY: require('assets/icon/icon-arrow_right_gray.png'),
  ICON_PLUS_ORANGE: require('assets/icon/icon_plus_orange.png'),
  POLYGON3: require('assets/icon/polygon-3.png'),
  PLAN_MANAGEMENT: {
    ARROW_LEFT: require('assets/image/planmanagement/arrow-left.png'),
    HUMAN: require('assets/image/planmanagement/person-running.png'),
    HEART: require('assets/image/planmanagement/heart.png'),
    VEGETABLE: require('assets/image/planmanagement/vegetable.png'),
    MEDICATION: require('assets/image/planmanagement/medication.png'),
    MEDICATION1: require('assets/image/planmanagement/medication1.png'),
    SHOES: require('assets/image/planmanagement/shoes.png'),
    SOCCER: require('assets/image/planmanagement/soccer.png'),
    BOLLING: require('assets/image/planmanagement/bolling.png'),
    BADMINTON: require('assets/image/planmanagement/badminton.png'),
    FORK_KNIFE: require('assets/image/planmanagement/fork-and-knife.png'),
    PEN_BOOK: require('assets/image/planmanagement/pen-and-book.png'),
  },
  PROFILE: {
    HOSPITAL_SCHEDULE: {
      TYPE1: require('assets/image/profile/anatomical-heart_1fac0_type1.png'),
      TYPE2: require('assets/image/profile/anatomical-heart_1fac0_type2.png'),
    },
  },
  QUESTION: {
    TEXT: require('assets/image/question/texting.png'),
    ICON_CHECK: require('assets/image/question/icon_check.png'),
  },
  RECORD_DATA: {
    BLOOD: require('assets/image/recordData/blood.png'),
    THERMOMETER: require('assets/image/recordData/thermometer.png'),
    CHART: require('assets/image/recordData/chart.png'),
    HEART_ORANGE: require('assets/image/recordData/heart_orange.png'),
    ICON_CHECK: require('assets/image/recordData/icon_check.png'),
    ICON_CHECK_ORANGE: require('assets/image/recordData/icon_check_orange1.png'),
    ICON_FACE_SMILES: require('assets/image/recordData/icon_face.png'),
    CALENDAR: require('assets/image/recordData/Category.png'),
  },
  EVALUATE: {
    NOTE: require('assets/image/evaluate/note.png'),
    HIGH: require('assets/image/evaluate/eval_high.png'),
    CONG1: require('assets/image/evaluate/cong1.png'),
    CONG2: require('assets/image/evaluate/cong2.png'),
    CONG3: require('assets/image/evaluate/cong3.png'),
    SAD1: require('assets/image/evaluate/icon_sad.png'),
    DOCTOR: require('assets/image/evaluate/icon__doctor.png'),
    CATEGORY: require('assets/image/evaluate/Category.png'),
  },
};
