export const offsetTime = 7
export enum Notification {
    DAILY_NOTIFICATION = "DAILY_NOTIFICATION",
    PLAN_NOTIFICATION = "PLAN_NOTIFICATION",
    WEEKLY_REPORT_NOTIFICATION = "WEEKLY_REPORT_NOTIFICATION",
    MONTHLY_REPORT_NOTIFICATION = "MONTHLY_REPORT_NOTIFICATION",
    QUESTION_NOTIFICATION = "QUESTION_NOTIFICATION",
    MEDICAL_APPOINTMENT_NOTIFICATION = "MEDICAL_APPOINTMENT_NOTIFICATION",
}