export const offsetTime = 7
export enum Notification {
    DAILY_NOTIFICATION = "DAILY_NOTIFICATION",
    PLAN_NOTIFICATION = "PLAN_NOTIFICATION",
    WEEKLY_REPORT_NOTIFICATION = "WEEKLY_REPORT_NOTIFICATION",
    MONTHLY_REPORT_NOTIFICATION = "MONTHLY_REPORT_NOTIFICATION",
    QUESTION_NOTIFICATION = "QUESTION_NOTIFICATION",
    MEDICAL_APPOINTMENT_NOTIFICATION = "MEDICAL_APPOINTMENT_NOTIFICATION",
}
export enum TypeQuestion {
    SAT_SF_C = "SAT_SF_C",
    SAT_SF_P = "SAT_SF_P",
    SAT_SF_I = "SAT_SF_I",
    SF_MEDICATION = "SF_MEDICATION",
    SF_MENTAL = "SF_MENTAL",
    SF_DIET = "SF_DIET",
    SF_ACTIVITY = "SF_ACTIVITY",
}